package b4a.example;

import anywheresoftware.b4a.BA;
import anywheresoftware.b4a.pc.*;

public class qurbanstewardshipdetail_subs_0 {


public static RemoteObject  _activity_create(RemoteObject _firsttime) throws Exception{
try {
		Debug.PushSubsStack("Activity_Create (qurbanstewardshipdetail) ","qurbanstewardshipdetail",21,qurbanstewardshipdetail.mostCurrent.activityBA,qurbanstewardshipdetail.mostCurrent,41);
if (RapidSub.canDelegate("activity_create")) return b4a.example.qurbanstewardshipdetail.remoteMe.runUserSub(false, "qurbanstewardshipdetail","activity_create", _firsttime);
Debug.locals.put("FirstTime", _firsttime);
 BA.debugLineNum = 41;BA.debugLine="Sub Activity_Create(FirstTime As Boolean)";
Debug.ShouldStop(256);
 BA.debugLineNum = 43;BA.debugLine="Activity.LoadLayout(\"MainScrollView\")";
Debug.ShouldStop(1024);
qurbanstewardshipdetail.mostCurrent._activity.runMethodAndSync(false,"LoadLayout",(Object)(RemoteObject.createImmutable("MainScrollView")),qurbanstewardshipdetail.mostCurrent.activityBA);
 BA.debugLineNum = 44;BA.debugLine="MainScroll.Panel.LoadLayout(\"DetailQurbanConfirma";
Debug.ShouldStop(2048);
qurbanstewardshipdetail.mostCurrent._mainscroll.runMethod(false,"getPanel").runMethodAndSync(false,"LoadLayout",(Object)(RemoteObject.createImmutable("DetailQurbanConfirmation")),qurbanstewardshipdetail.mostCurrent.activityBA);
 BA.debugLineNum = 45;BA.debugLine="MainScroll.Panel.Height= PanelQurban.Height";
Debug.ShouldStop(4096);
qurbanstewardshipdetail.mostCurrent._mainscroll.runMethod(false,"getPanel").runMethod(true,"setHeight",qurbanstewardshipdetail.mostCurrent._panelqurban.runMethod(true,"getHeight"));
 BA.debugLineNum = 46;BA.debugLine="MainScroll.Height = 100%y - MainScroll.Top";
Debug.ShouldStop(8192);
qurbanstewardshipdetail.mostCurrent._mainscroll.runMethod(true,"setHeight",RemoteObject.solve(new RemoteObject[] {qurbanstewardshipdetail.mostCurrent.__c.runMethod(true,"PerYToCurrent",(Object)(BA.numberCast(float.class, 100)),qurbanstewardshipdetail.mostCurrent.activityBA),qurbanstewardshipdetail.mostCurrent._mainscroll.runMethod(true,"getTop")}, "-",1, 1));
 BA.debugLineNum = 48;BA.debugLine="NavbarTitle.Text=\"Qurban Detail\"";
Debug.ShouldStop(32768);
qurbanstewardshipdetail.mostCurrent._navbartitle.runMethod(true,"setText",BA.ObjectToCharSequence("Qurban Detail"));
 BA.debugLineNum = 49;BA.debugLine="NavbarTitle.TextSize = 20";
Debug.ShouldStop(65536);
qurbanstewardshipdetail.mostCurrent._navbartitle.runMethod(true,"setTextSize",BA.numberCast(float.class, 20));
 BA.debugLineNum = 50;BA.debugLine="End Sub";
Debug.ShouldStop(131072);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _activity_pause(RemoteObject _userclosed) throws Exception{
try {
		Debug.PushSubsStack("Activity_Pause (qurbanstewardshipdetail) ","qurbanstewardshipdetail",21,qurbanstewardshipdetail.mostCurrent.activityBA,qurbanstewardshipdetail.mostCurrent,56);
if (RapidSub.canDelegate("activity_pause")) return b4a.example.qurbanstewardshipdetail.remoteMe.runUserSub(false, "qurbanstewardshipdetail","activity_pause", _userclosed);
Debug.locals.put("UserClosed", _userclosed);
 BA.debugLineNum = 56;BA.debugLine="Sub Activity_Pause (UserClosed As Boolean)";
Debug.ShouldStop(8388608);
 BA.debugLineNum = 58;BA.debugLine="End Sub";
Debug.ShouldStop(33554432);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _activity_resume() throws Exception{
try {
		Debug.PushSubsStack("Activity_Resume (qurbanstewardshipdetail) ","qurbanstewardshipdetail",21,qurbanstewardshipdetail.mostCurrent.activityBA,qurbanstewardshipdetail.mostCurrent,52);
if (RapidSub.canDelegate("activity_resume")) return b4a.example.qurbanstewardshipdetail.remoteMe.runUserSub(false, "qurbanstewardshipdetail","activity_resume");
 BA.debugLineNum = 52;BA.debugLine="Sub Activity_Resume";
Debug.ShouldStop(524288);
 BA.debugLineNum = 53;BA.debugLine="CodeSemua.ExecuteUrlGet(Main.server&\"api/qurban/c";
Debug.ShouldStop(1048576);
qurbanstewardshipdetail.mostCurrent._codesemua.runVoidMethod ("_executeurlget",qurbanstewardshipdetail.mostCurrent.activityBA,(Object)(RemoteObject.concat(qurbanstewardshipdetail.mostCurrent._main._server,RemoteObject.createImmutable("api/qurban/confirmation/detail?id="),qurbanstewardshipdetail.mostCurrent._qurbanstewardship._idselected)),(Object)(BA.ObjectToString("LoadData")),(Object)(qurbanstewardshipdetail.getObject()));
 BA.debugLineNum = 54;BA.debugLine="End Sub";
Debug.ShouldStop(2097152);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _btnconfirm_click() throws Exception{
try {
		Debug.PushSubsStack("BtnConfirm_Click (qurbanstewardshipdetail) ","qurbanstewardshipdetail",21,qurbanstewardshipdetail.mostCurrent.activityBA,qurbanstewardshipdetail.mostCurrent,388);
if (RapidSub.canDelegate("btnconfirm_click")) return b4a.example.qurbanstewardshipdetail.remoteMe.runUserSub(false, "qurbanstewardshipdetail","btnconfirm_click");
 BA.debugLineNum = 388;BA.debugLine="Sub BtnConfirm_Click";
Debug.ShouldStop(8);
 BA.debugLineNum = 389;BA.debugLine="CodeSemua.ExecuteUrlGet(Main.server&\"api/qurban/c";
Debug.ShouldStop(16);
qurbanstewardshipdetail.mostCurrent._codesemua.runVoidMethod ("_executeurlget",qurbanstewardshipdetail.mostCurrent.activityBA,(Object)(RemoteObject.concat(qurbanstewardshipdetail.mostCurrent._main._server,RemoteObject.createImmutable("api/qurban/confirmation/store?id="),qurbanstewardshipdetail.mostCurrent._qurbanstewardship._idselected)),(Object)(BA.ObjectToString("success")),(Object)(qurbanstewardshipdetail.getObject()));
 BA.debugLineNum = 390;BA.debugLine="Msgbox(\"Transaction Qurban #\"&QurbanStewardship.i";
Debug.ShouldStop(32);
qurbanstewardshipdetail.mostCurrent.__c.runVoidMethodAndSync ("Msgbox",(Object)(BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("Transaction Qurban #"),qurbanstewardshipdetail.mostCurrent._qurbanstewardship._idselected,RemoteObject.createImmutable(" confirmed!")))),(Object)(BA.ObjectToCharSequence(RemoteObject.createImmutable("Confirmation Success!"))),qurbanstewardshipdetail.mostCurrent.activityBA);
 BA.debugLineNum = 391;BA.debugLine="End Sub";
Debug.ShouldStop(64);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _globals() throws Exception{
 //BA.debugLineNum = 12;BA.debugLine="Sub Globals";
 //BA.debugLineNum = 15;BA.debugLine="Private MainScroll As ScrollView";
qurbanstewardshipdetail.mostCurrent._mainscroll = RemoteObject.createNew ("anywheresoftware.b4a.objects.ScrollViewWrapper");
 //BA.debugLineNum = 16;BA.debugLine="Private PanelQurban As Panel";
qurbanstewardshipdetail.mostCurrent._panelqurban = RemoteObject.createNew ("anywheresoftware.b4a.objects.PanelWrapper");
 //BA.debugLineNum = 17;BA.debugLine="Private BtnConfirm As Button";
qurbanstewardshipdetail.mostCurrent._btnconfirm = RemoteObject.createNew ("anywheresoftware.b4a.objects.ButtonWrapper");
 //BA.debugLineNum = 18;BA.debugLine="Private NavbarTitle As Label";
qurbanstewardshipdetail.mostCurrent._navbartitle = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 19;BA.debugLine="Private Label2 As Label";
qurbanstewardshipdetail.mostCurrent._label2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 20;BA.debugLine="Private Label1 As Label";
qurbanstewardshipdetail.mostCurrent._label1 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 21;BA.debugLine="Private Label4 As Label";
qurbanstewardshipdetail.mostCurrent._label4 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 22;BA.debugLine="Private Label10 As Label";
qurbanstewardshipdetail.mostCurrent._label10 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 23;BA.debugLine="Private Label12 As Label";
qurbanstewardshipdetail.mostCurrent._label12 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 24;BA.debugLine="Private Note As Label";
qurbanstewardshipdetail.mostCurrent._note = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 25;BA.debugLine="Private Label5 As Label";
qurbanstewardshipdetail.mostCurrent._label5 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 26;BA.debugLine="Private Label6 As Label";
qurbanstewardshipdetail.mostCurrent._label6 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 27;BA.debugLine="Private Label7 As Label";
qurbanstewardshipdetail.mostCurrent._label7 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 28;BA.debugLine="Private Label8 As Label";
qurbanstewardshipdetail.mostCurrent._label8 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 29;BA.debugLine="Private Part2 As Label";
qurbanstewardshipdetail.mostCurrent._part2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 30;BA.debugLine="Private Part3 As Label";
qurbanstewardshipdetail.mostCurrent._part3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 31;BA.debugLine="Private Part4 As Label";
qurbanstewardshipdetail.mostCurrent._part4 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 32;BA.debugLine="Private Part5 As Label";
qurbanstewardshipdetail.mostCurrent._part5 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 33;BA.debugLine="Private Part6 As Label";
qurbanstewardshipdetail.mostCurrent._part6 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 34;BA.debugLine="Private Part7 As Label";
qurbanstewardshipdetail.mostCurrent._part7 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 35;BA.debugLine="Private Part8 As Label";
qurbanstewardshipdetail.mostCurrent._part8 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 36;BA.debugLine="Private Part9 As Label";
qurbanstewardshipdetail.mostCurrent._part9 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 37;BA.debugLine="Private Part10 As Label";
qurbanstewardshipdetail.mostCurrent._part10 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 38;BA.debugLine="Private Part11 As Label";
qurbanstewardshipdetail.mostCurrent._part11 = RemoteObject.createNew ("anywheresoftware.b4a.objects.LabelWrapper");
 //BA.debugLineNum = 39;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
public static RemoteObject  _jobdone(RemoteObject _job) throws Exception{
try {
		Debug.PushSubsStack("JobDone (qurbanstewardshipdetail) ","qurbanstewardshipdetail",21,qurbanstewardshipdetail.mostCurrent.activityBA,qurbanstewardshipdetail.mostCurrent,60);
if (RapidSub.canDelegate("jobdone")) return b4a.example.qurbanstewardshipdetail.remoteMe.runUserSub(false, "qurbanstewardshipdetail","jobdone", _job);
RemoteObject _res = RemoteObject.createImmutable("");
RemoteObject _parser = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.JSONParser");
RemoteObject _b = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _info = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _participant = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
RemoteObject _status = RemoteObject.createImmutable("");
RemoteObject _part_2 = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _part_3 = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _part_4 = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _part_5 = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _part_6 = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _part_7 = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _part_8 = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _part_9 = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _part_10 = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
RemoteObject _part_11 = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.Map");
Debug.locals.put("Job", _job);
 BA.debugLineNum = 60;BA.debugLine="Sub JobDone (Job As HttpJob)";
Debug.ShouldStop(134217728);
 BA.debugLineNum = 62;BA.debugLine="If Job.Success = True Then";
Debug.ShouldStop(536870912);
if (RemoteObject.solveBoolean("=",_job.getField(true,"_success"),qurbanstewardshipdetail.mostCurrent.__c.getField(true,"True"))) { 
 BA.debugLineNum = 63;BA.debugLine="Dim res As String";
Debug.ShouldStop(1073741824);
_res = RemoteObject.createImmutable("");Debug.locals.put("res", _res);
 BA.debugLineNum = 64;BA.debugLine="res = Job.GetString 'menyimpan json dalam bentuk";
Debug.ShouldStop(-2147483648);
_res = _job.runMethod(true,"_getstring");Debug.locals.put("res", _res);
 BA.debugLineNum = 66;BA.debugLine="Dim parser As JSONParser 'mengambil data dalam b";
Debug.ShouldStop(2);
_parser = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.JSONParser");Debug.locals.put("parser", _parser);
 BA.debugLineNum = 67;BA.debugLine="parser.Initialize(res)";
Debug.ShouldStop(4);
_parser.runVoidMethod ("Initialize",(Object)(_res));
 BA.debugLineNum = 69;BA.debugLine="Log(\"Response from server-------------- :\"& res)";
Debug.ShouldStop(16);
qurbanstewardshipdetail.mostCurrent.__c.runVoidMethod ("Log",(Object)(RemoteObject.concat(RemoteObject.createImmutable("Response from server-------------- :"),_res)));
 BA.debugLineNum = 71;BA.debugLine="If Job.JobName = \"success\" Then";
Debug.ShouldStop(64);
if (RemoteObject.solveBoolean("=",_job.getField(true,"_jobname"),BA.ObjectToString("success"))) { 
 BA.debugLineNum = 72;BA.debugLine="Activity.Finish";
Debug.ShouldStop(128);
qurbanstewardshipdetail.mostCurrent._activity.runVoidMethod ("Finish");
 BA.debugLineNum = 73;BA.debugLine="StartActivity(Me)";
Debug.ShouldStop(256);
qurbanstewardshipdetail.mostCurrent.__c.runVoidMethod ("StartActivity",qurbanstewardshipdetail.processBA,(Object)(qurbanstewardshipdetail.getObject()));
 };
 BA.debugLineNum = 76;BA.debugLine="Select Job.JobName";
Debug.ShouldStop(2048);
switch (BA.switchObjectToInt(_job.getField(true,"_jobname"),BA.ObjectToString("LoadData"))) {
case 0: {
 BA.debugLineNum = 78;BA.debugLine="Try";
Debug.ShouldStop(8192);
try { BA.debugLineNum = 79;BA.debugLine="Dim parser As JSONParser";
Debug.ShouldStop(16384);
_parser = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.JSONParser");Debug.locals.put("parser", _parser);
 BA.debugLineNum = 80;BA.debugLine="parser.Initialize(Job.GetString)";
Debug.ShouldStop(32768);
_parser.runVoidMethod ("Initialize",(Object)(_job.runMethod(true,"_getstring")));
 BA.debugLineNum = 81;BA.debugLine="Dim b As Map = parser.NextObject";
Debug.ShouldStop(65536);
_b = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");
_b = _parser.runMethod(false,"NextObject");Debug.locals.put("b", _b);Debug.locals.put("b", _b);
 BA.debugLineNum = 83;BA.debugLine="Dim info As Map : info.Initialize";
Debug.ShouldStop(262144);
_info = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("info", _info);
 BA.debugLineNum = 83;BA.debugLine="Dim info As Map : info.Initialize";
Debug.ShouldStop(262144);
_info.runVoidMethod ("Initialize");
 BA.debugLineNum = 84;BA.debugLine="info = b.Get(\"info\")";
Debug.ShouldStop(524288);
_info.setObject(_b.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("info")))));
 BA.debugLineNum = 86;BA.debugLine="Dim participant As List : participant.Initial";
Debug.ShouldStop(2097152);
_participant = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.List");Debug.locals.put("participant", _participant);
 BA.debugLineNum = 86;BA.debugLine="Dim participant As List : participant.Initial";
Debug.ShouldStop(2097152);
_participant.runVoidMethod ("Initialize");
 BA.debugLineNum = 87;BA.debugLine="participant = b.Get(\"participant\")";
Debug.ShouldStop(4194304);
_participant.setObject(_b.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("participant")))));
 BA.debugLineNum = 89;BA.debugLine="Label4.Text = \": \"&info.Get(\"animal_type\")";
Debug.ShouldStop(16777216);
qurbanstewardshipdetail.mostCurrent._label4.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(": "),_info.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("animal_type")))))));
 BA.debugLineNum = 90;BA.debugLine="Label6.Text = \": \"&info.Get(\"fund\")";
Debug.ShouldStop(33554432);
qurbanstewardshipdetail.mostCurrent._label6.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(": "),_info.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("fund")))))));
 BA.debugLineNum = 91;BA.debugLine="Label8.Text = \": \"&info.Get(\"datetime\")";
Debug.ShouldStop(67108864);
qurbanstewardshipdetail.mostCurrent._label8.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(": "),_info.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("datetime")))))));
 BA.debugLineNum = 92;BA.debugLine="Dim status As String = info.Get(\"confirmation";
Debug.ShouldStop(134217728);
_status = BA.ObjectToString(_info.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("confirmation")))));Debug.locals.put("status", _status);Debug.locals.put("status", _status);
 BA.debugLineNum = 93;BA.debugLine="If status = False Then";
Debug.ShouldStop(268435456);
if (RemoteObject.solveBoolean("=",_status,BA.ObjectToString(qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False")))) { 
 BA.debugLineNum = 94;BA.debugLine="Label12.Text = \": Checking\"";
Debug.ShouldStop(536870912);
qurbanstewardshipdetail.mostCurrent._label12.runMethod(true,"setText",BA.ObjectToCharSequence(": Checking"));
 BA.debugLineNum = 95;BA.debugLine="Label12.TextColor = Colors.Red";
Debug.ShouldStop(1073741824);
qurbanstewardshipdetail.mostCurrent._label12.runMethod(true,"setTextColor",qurbanstewardshipdetail.mostCurrent.__c.getField(false,"Colors").getField(true,"Red"));
 }else {
 BA.debugLineNum = 97;BA.debugLine="Label12.Text = \": Confirmed\"";
Debug.ShouldStop(1);
qurbanstewardshipdetail.mostCurrent._label12.runMethod(true,"setText",BA.ObjectToCharSequence(": Confirmed"));
 BA.debugLineNum = 98;BA.debugLine="Label12.TextColor = Colors.Green";
Debug.ShouldStop(2);
qurbanstewardshipdetail.mostCurrent._label12.runMethod(true,"setTextColor",qurbanstewardshipdetail.mostCurrent.__c.getField(false,"Colors").getField(true,"Green"));
 };
 BA.debugLineNum = 101;BA.debugLine="If participant.Size = 1 Then";
Debug.ShouldStop(16);
if (RemoteObject.solveBoolean("=",_participant.runMethod(true,"getSize"),BA.numberCast(double.class, 1))) { 
 BA.debugLineNum = 102;BA.debugLine="Dim part_2 As Map";
Debug.ShouldStop(32);
_part_2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_2", _part_2);
 BA.debugLineNum = 103;BA.debugLine="part_2 = participant.Get(0)";
Debug.ShouldStop(64);
_part_2.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 0))));
 BA.debugLineNum = 104;BA.debugLine="Part2.Text = \" - \"&part_2.Get(\"name\")";
Debug.ShouldStop(128);
qurbanstewardshipdetail.mostCurrent._part2.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_2.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 106;BA.debugLine="Part3.Visible = False";
Debug.ShouldStop(512);
qurbanstewardshipdetail.mostCurrent._part3.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 107;BA.debugLine="Part4.Visible = False";
Debug.ShouldStop(1024);
qurbanstewardshipdetail.mostCurrent._part4.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 108;BA.debugLine="Part5.Visible = False";
Debug.ShouldStop(2048);
qurbanstewardshipdetail.mostCurrent._part5.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 109;BA.debugLine="Part6.Visible = False";
Debug.ShouldStop(4096);
qurbanstewardshipdetail.mostCurrent._part6.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 110;BA.debugLine="Part7.Visible = False";
Debug.ShouldStop(8192);
qurbanstewardshipdetail.mostCurrent._part7.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 111;BA.debugLine="Part8.Visible = False";
Debug.ShouldStop(16384);
qurbanstewardshipdetail.mostCurrent._part8.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 112;BA.debugLine="Part9.Visible = False";
Debug.ShouldStop(32768);
qurbanstewardshipdetail.mostCurrent._part9.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 113;BA.debugLine="Part10.Visible = False";
Debug.ShouldStop(65536);
qurbanstewardshipdetail.mostCurrent._part10.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 114;BA.debugLine="Part11.Visible = False";
Debug.ShouldStop(131072);
qurbanstewardshipdetail.mostCurrent._part11.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 }else 
{ BA.debugLineNum = 115;BA.debugLine="Else If participant.Size = 2 Then";
Debug.ShouldStop(262144);
if (RemoteObject.solveBoolean("=",_participant.runMethod(true,"getSize"),BA.numberCast(double.class, 2))) { 
 BA.debugLineNum = 116;BA.debugLine="Dim part_2 As Map";
Debug.ShouldStop(524288);
_part_2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_2", _part_2);
 BA.debugLineNum = 117;BA.debugLine="part_2 = participant.Get(0)";
Debug.ShouldStop(1048576);
_part_2.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 0))));
 BA.debugLineNum = 118;BA.debugLine="Part2.Text = \" - \"&part_2.Get(\"name\")";
Debug.ShouldStop(2097152);
qurbanstewardshipdetail.mostCurrent._part2.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_2.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 120;BA.debugLine="Dim part_3 As Map";
Debug.ShouldStop(8388608);
_part_3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_3", _part_3);
 BA.debugLineNum = 121;BA.debugLine="part_3 = participant.Get(1)";
Debug.ShouldStop(16777216);
_part_3.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 1))));
 BA.debugLineNum = 122;BA.debugLine="Part3.Text = \" - \"&part_3.Get(\"name\")";
Debug.ShouldStop(33554432);
qurbanstewardshipdetail.mostCurrent._part3.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_3.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 124;BA.debugLine="Part4.Visible = False";
Debug.ShouldStop(134217728);
qurbanstewardshipdetail.mostCurrent._part4.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 125;BA.debugLine="Part5.Visible = False";
Debug.ShouldStop(268435456);
qurbanstewardshipdetail.mostCurrent._part5.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 126;BA.debugLine="Part6.Visible = False";
Debug.ShouldStop(536870912);
qurbanstewardshipdetail.mostCurrent._part6.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 127;BA.debugLine="Part7.Visible = False";
Debug.ShouldStop(1073741824);
qurbanstewardshipdetail.mostCurrent._part7.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 128;BA.debugLine="Part8.Visible = False";
Debug.ShouldStop(-2147483648);
qurbanstewardshipdetail.mostCurrent._part8.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 129;BA.debugLine="Part9.Visible = False";
Debug.ShouldStop(1);
qurbanstewardshipdetail.mostCurrent._part9.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 130;BA.debugLine="Part10.Visible = False";
Debug.ShouldStop(2);
qurbanstewardshipdetail.mostCurrent._part10.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 131;BA.debugLine="Part11.Visible = False";
Debug.ShouldStop(4);
qurbanstewardshipdetail.mostCurrent._part11.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 }else 
{ BA.debugLineNum = 132;BA.debugLine="Else If participant.Size = 3 Then";
Debug.ShouldStop(8);
if (RemoteObject.solveBoolean("=",_participant.runMethod(true,"getSize"),BA.numberCast(double.class, 3))) { 
 BA.debugLineNum = 133;BA.debugLine="Dim part_2 As Map";
Debug.ShouldStop(16);
_part_2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_2", _part_2);
 BA.debugLineNum = 134;BA.debugLine="part_2 = participant.Get(0)";
Debug.ShouldStop(32);
_part_2.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 0))));
 BA.debugLineNum = 135;BA.debugLine="Part2.Text = \" - \"&part_2.Get(\"name\")";
Debug.ShouldStop(64);
qurbanstewardshipdetail.mostCurrent._part2.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_2.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 137;BA.debugLine="Dim part_3 As Map";
Debug.ShouldStop(256);
_part_3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_3", _part_3);
 BA.debugLineNum = 138;BA.debugLine="part_3 = participant.Get(1)";
Debug.ShouldStop(512);
_part_3.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 1))));
 BA.debugLineNum = 139;BA.debugLine="Part3.Text = \" - \"&part_3.Get(\"name\")";
Debug.ShouldStop(1024);
qurbanstewardshipdetail.mostCurrent._part3.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_3.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 141;BA.debugLine="Dim part_4 As Map";
Debug.ShouldStop(4096);
_part_4 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_4", _part_4);
 BA.debugLineNum = 142;BA.debugLine="part_4 = participant.Get(2)";
Debug.ShouldStop(8192);
_part_4.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 2))));
 BA.debugLineNum = 143;BA.debugLine="Part4.Text = \" - \"&part_4.Get(\"name\")";
Debug.ShouldStop(16384);
qurbanstewardshipdetail.mostCurrent._part4.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_4.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 145;BA.debugLine="Part5.Visible = False";
Debug.ShouldStop(65536);
qurbanstewardshipdetail.mostCurrent._part5.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 146;BA.debugLine="Part6.Visible = False";
Debug.ShouldStop(131072);
qurbanstewardshipdetail.mostCurrent._part6.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 147;BA.debugLine="Part7.Visible = False";
Debug.ShouldStop(262144);
qurbanstewardshipdetail.mostCurrent._part7.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 148;BA.debugLine="Part8.Visible = False";
Debug.ShouldStop(524288);
qurbanstewardshipdetail.mostCurrent._part8.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 149;BA.debugLine="Part9.Visible = False";
Debug.ShouldStop(1048576);
qurbanstewardshipdetail.mostCurrent._part9.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 150;BA.debugLine="Part10.Visible = False";
Debug.ShouldStop(2097152);
qurbanstewardshipdetail.mostCurrent._part10.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 151;BA.debugLine="Part11.Visible = False";
Debug.ShouldStop(4194304);
qurbanstewardshipdetail.mostCurrent._part11.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 }else 
{ BA.debugLineNum = 152;BA.debugLine="Else If participant.Size = 4 Then";
Debug.ShouldStop(8388608);
if (RemoteObject.solveBoolean("=",_participant.runMethod(true,"getSize"),BA.numberCast(double.class, 4))) { 
 BA.debugLineNum = 153;BA.debugLine="Dim part_2 As Map";
Debug.ShouldStop(16777216);
_part_2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_2", _part_2);
 BA.debugLineNum = 154;BA.debugLine="part_2 = participant.Get(0)";
Debug.ShouldStop(33554432);
_part_2.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 0))));
 BA.debugLineNum = 155;BA.debugLine="Part2.Text = \" - \"&part_2.Get(\"name\")";
Debug.ShouldStop(67108864);
qurbanstewardshipdetail.mostCurrent._part2.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_2.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 157;BA.debugLine="Dim part_3 As Map";
Debug.ShouldStop(268435456);
_part_3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_3", _part_3);
 BA.debugLineNum = 158;BA.debugLine="part_3 = participant.Get(1)";
Debug.ShouldStop(536870912);
_part_3.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 1))));
 BA.debugLineNum = 159;BA.debugLine="Part3.Text = \" - \"&part_3.Get(\"name\")";
Debug.ShouldStop(1073741824);
qurbanstewardshipdetail.mostCurrent._part3.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_3.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 161;BA.debugLine="Dim part_4 As Map";
Debug.ShouldStop(1);
_part_4 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_4", _part_4);
 BA.debugLineNum = 162;BA.debugLine="part_4 = participant.Get(2)";
Debug.ShouldStop(2);
_part_4.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 2))));
 BA.debugLineNum = 163;BA.debugLine="Part4.Text = \" - \"&part_4.Get(\"name\")";
Debug.ShouldStop(4);
qurbanstewardshipdetail.mostCurrent._part4.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_4.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 165;BA.debugLine="Dim part_5 As Map";
Debug.ShouldStop(16);
_part_5 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_5", _part_5);
 BA.debugLineNum = 166;BA.debugLine="part_5 = participant.Get(3)";
Debug.ShouldStop(32);
_part_5.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 3))));
 BA.debugLineNum = 167;BA.debugLine="Part5.Text = \" - \"&part_5.Get(\"name\")";
Debug.ShouldStop(64);
qurbanstewardshipdetail.mostCurrent._part5.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_5.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 169;BA.debugLine="Part6.Visible = False";
Debug.ShouldStop(256);
qurbanstewardshipdetail.mostCurrent._part6.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 170;BA.debugLine="Part7.Visible = False";
Debug.ShouldStop(512);
qurbanstewardshipdetail.mostCurrent._part7.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 171;BA.debugLine="Part8.Visible = False";
Debug.ShouldStop(1024);
qurbanstewardshipdetail.mostCurrent._part8.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 172;BA.debugLine="Part9.Visible = False";
Debug.ShouldStop(2048);
qurbanstewardshipdetail.mostCurrent._part9.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 173;BA.debugLine="Part10.Visible = False";
Debug.ShouldStop(4096);
qurbanstewardshipdetail.mostCurrent._part10.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 174;BA.debugLine="Part11.Visible = False";
Debug.ShouldStop(8192);
qurbanstewardshipdetail.mostCurrent._part11.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 }else 
{ BA.debugLineNum = 175;BA.debugLine="Else If participant.Size = 5 Then";
Debug.ShouldStop(16384);
if (RemoteObject.solveBoolean("=",_participant.runMethod(true,"getSize"),BA.numberCast(double.class, 5))) { 
 BA.debugLineNum = 176;BA.debugLine="Dim part_2 As Map";
Debug.ShouldStop(32768);
_part_2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_2", _part_2);
 BA.debugLineNum = 177;BA.debugLine="part_2 = participant.Get(0)";
Debug.ShouldStop(65536);
_part_2.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 0))));
 BA.debugLineNum = 178;BA.debugLine="Part2.Text = \" - \"&part_2.Get(\"name\")";
Debug.ShouldStop(131072);
qurbanstewardshipdetail.mostCurrent._part2.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_2.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 180;BA.debugLine="Dim part_3 As Map";
Debug.ShouldStop(524288);
_part_3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_3", _part_3);
 BA.debugLineNum = 181;BA.debugLine="part_3 = participant.Get(1)";
Debug.ShouldStop(1048576);
_part_3.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 1))));
 BA.debugLineNum = 182;BA.debugLine="Part3.Text = \" - \"&part_3.Get(\"name\")";
Debug.ShouldStop(2097152);
qurbanstewardshipdetail.mostCurrent._part3.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_3.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 184;BA.debugLine="Dim part_4 As Map";
Debug.ShouldStop(8388608);
_part_4 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_4", _part_4);
 BA.debugLineNum = 185;BA.debugLine="part_4 = participant.Get(2)";
Debug.ShouldStop(16777216);
_part_4.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 2))));
 BA.debugLineNum = 186;BA.debugLine="Part4.Text = \" - \"&part_4.Get(\"name\")";
Debug.ShouldStop(33554432);
qurbanstewardshipdetail.mostCurrent._part4.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_4.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 188;BA.debugLine="Dim part_5 As Map";
Debug.ShouldStop(134217728);
_part_5 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_5", _part_5);
 BA.debugLineNum = 189;BA.debugLine="part_5 = participant.Get(3)";
Debug.ShouldStop(268435456);
_part_5.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 3))));
 BA.debugLineNum = 190;BA.debugLine="Part5.Text = \" - \"&part_5.Get(\"name\")";
Debug.ShouldStop(536870912);
qurbanstewardshipdetail.mostCurrent._part5.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_5.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 192;BA.debugLine="Dim part_6 As Map";
Debug.ShouldStop(-2147483648);
_part_6 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_6", _part_6);
 BA.debugLineNum = 193;BA.debugLine="part_6 = participant.Get(4)";
Debug.ShouldStop(1);
_part_6.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 4))));
 BA.debugLineNum = 194;BA.debugLine="Part6.Text = \" - \"&part_6.Get(\"name\")";
Debug.ShouldStop(2);
qurbanstewardshipdetail.mostCurrent._part6.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_6.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 196;BA.debugLine="Part7.Visible = False";
Debug.ShouldStop(8);
qurbanstewardshipdetail.mostCurrent._part7.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 197;BA.debugLine="Part8.Visible = False";
Debug.ShouldStop(16);
qurbanstewardshipdetail.mostCurrent._part8.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 198;BA.debugLine="Part9.Visible = False";
Debug.ShouldStop(32);
qurbanstewardshipdetail.mostCurrent._part9.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 199;BA.debugLine="Part10.Visible = False";
Debug.ShouldStop(64);
qurbanstewardshipdetail.mostCurrent._part10.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 200;BA.debugLine="Part11.Visible = False";
Debug.ShouldStop(128);
qurbanstewardshipdetail.mostCurrent._part11.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 }else 
{ BA.debugLineNum = 201;BA.debugLine="Else If participant.Size = 6 Then";
Debug.ShouldStop(256);
if (RemoteObject.solveBoolean("=",_participant.runMethod(true,"getSize"),BA.numberCast(double.class, 6))) { 
 BA.debugLineNum = 202;BA.debugLine="Dim part_2 As Map";
Debug.ShouldStop(512);
_part_2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_2", _part_2);
 BA.debugLineNum = 203;BA.debugLine="part_2 = participant.Get(0)";
Debug.ShouldStop(1024);
_part_2.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 0))));
 BA.debugLineNum = 204;BA.debugLine="Part2.Text = \" - \"&part_2.Get(\"name\")";
Debug.ShouldStop(2048);
qurbanstewardshipdetail.mostCurrent._part2.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_2.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 206;BA.debugLine="Dim part_3 As Map";
Debug.ShouldStop(8192);
_part_3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_3", _part_3);
 BA.debugLineNum = 207;BA.debugLine="part_3 = participant.Get(1)";
Debug.ShouldStop(16384);
_part_3.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 1))));
 BA.debugLineNum = 208;BA.debugLine="Part3.Text = \" - \"&part_3.Get(\"name\")";
Debug.ShouldStop(32768);
qurbanstewardshipdetail.mostCurrent._part3.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_3.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 210;BA.debugLine="Dim part_4 As Map";
Debug.ShouldStop(131072);
_part_4 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_4", _part_4);
 BA.debugLineNum = 211;BA.debugLine="part_4 = participant.Get(2)";
Debug.ShouldStop(262144);
_part_4.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 2))));
 BA.debugLineNum = 212;BA.debugLine="Part4.Text = \" - \"&part_4.Get(\"name\")";
Debug.ShouldStop(524288);
qurbanstewardshipdetail.mostCurrent._part4.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_4.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 214;BA.debugLine="Dim part_5 As Map";
Debug.ShouldStop(2097152);
_part_5 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_5", _part_5);
 BA.debugLineNum = 215;BA.debugLine="part_5 = participant.Get(3)";
Debug.ShouldStop(4194304);
_part_5.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 3))));
 BA.debugLineNum = 216;BA.debugLine="Part5.Text = \" - \"&part_5.Get(\"name\")";
Debug.ShouldStop(8388608);
qurbanstewardshipdetail.mostCurrent._part5.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_5.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 218;BA.debugLine="Dim part_6 As Map";
Debug.ShouldStop(33554432);
_part_6 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_6", _part_6);
 BA.debugLineNum = 219;BA.debugLine="part_6 = participant.Get(4)";
Debug.ShouldStop(67108864);
_part_6.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 4))));
 BA.debugLineNum = 220;BA.debugLine="Part6.Text = \" - \"&part_6.Get(\"name\")";
Debug.ShouldStop(134217728);
qurbanstewardshipdetail.mostCurrent._part6.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_6.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 222;BA.debugLine="Dim part_7 As Map";
Debug.ShouldStop(536870912);
_part_7 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_7", _part_7);
 BA.debugLineNum = 223;BA.debugLine="part_7 = participant.Get(5)";
Debug.ShouldStop(1073741824);
_part_7.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 5))));
 BA.debugLineNum = 224;BA.debugLine="Part7.Text = \" - \"&part_7.Get(\"name\")";
Debug.ShouldStop(-2147483648);
qurbanstewardshipdetail.mostCurrent._part7.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_7.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 226;BA.debugLine="Part8.Visible = False";
Debug.ShouldStop(2);
qurbanstewardshipdetail.mostCurrent._part8.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 227;BA.debugLine="Part9.Visible = False";
Debug.ShouldStop(4);
qurbanstewardshipdetail.mostCurrent._part9.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 228;BA.debugLine="Part10.Visible = False";
Debug.ShouldStop(8);
qurbanstewardshipdetail.mostCurrent._part10.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 229;BA.debugLine="Part11.Visible = False";
Debug.ShouldStop(16);
qurbanstewardshipdetail.mostCurrent._part11.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 }else 
{ BA.debugLineNum = 230;BA.debugLine="Else If participant.Size = 7 Then";
Debug.ShouldStop(32);
if (RemoteObject.solveBoolean("=",_participant.runMethod(true,"getSize"),BA.numberCast(double.class, 7))) { 
 BA.debugLineNum = 231;BA.debugLine="Dim part_2 As Map";
Debug.ShouldStop(64);
_part_2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_2", _part_2);
 BA.debugLineNum = 232;BA.debugLine="part_2 = participant.Get(0)";
Debug.ShouldStop(128);
_part_2.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 0))));
 BA.debugLineNum = 233;BA.debugLine="Part2.Text = \" - \"&part_2.Get(\"name\")";
Debug.ShouldStop(256);
qurbanstewardshipdetail.mostCurrent._part2.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_2.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 235;BA.debugLine="Dim part_3 As Map";
Debug.ShouldStop(1024);
_part_3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_3", _part_3);
 BA.debugLineNum = 236;BA.debugLine="part_3 = participant.Get(1)";
Debug.ShouldStop(2048);
_part_3.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 1))));
 BA.debugLineNum = 237;BA.debugLine="Part3.Text = \" - \"&part_3.Get(\"name\")";
Debug.ShouldStop(4096);
qurbanstewardshipdetail.mostCurrent._part3.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_3.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 239;BA.debugLine="Dim part_4 As Map";
Debug.ShouldStop(16384);
_part_4 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_4", _part_4);
 BA.debugLineNum = 240;BA.debugLine="part_4 = participant.Get(2)";
Debug.ShouldStop(32768);
_part_4.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 2))));
 BA.debugLineNum = 241;BA.debugLine="Part4.Text = \" - \"&part_4.Get(\"name\")";
Debug.ShouldStop(65536);
qurbanstewardshipdetail.mostCurrent._part4.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_4.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 243;BA.debugLine="Dim part_5 As Map";
Debug.ShouldStop(262144);
_part_5 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_5", _part_5);
 BA.debugLineNum = 244;BA.debugLine="part_5 = participant.Get(3)";
Debug.ShouldStop(524288);
_part_5.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 3))));
 BA.debugLineNum = 245;BA.debugLine="Part5.Text = \" - \"&part_5.Get(\"name\")";
Debug.ShouldStop(1048576);
qurbanstewardshipdetail.mostCurrent._part5.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_5.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 247;BA.debugLine="Dim part_6 As Map";
Debug.ShouldStop(4194304);
_part_6 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_6", _part_6);
 BA.debugLineNum = 248;BA.debugLine="part_6 = participant.Get(4)";
Debug.ShouldStop(8388608);
_part_6.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 4))));
 BA.debugLineNum = 249;BA.debugLine="Part6.Text = \" - \"&part_6.Get(\"name\")";
Debug.ShouldStop(16777216);
qurbanstewardshipdetail.mostCurrent._part6.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_6.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 251;BA.debugLine="Dim part_7 As Map";
Debug.ShouldStop(67108864);
_part_7 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_7", _part_7);
 BA.debugLineNum = 252;BA.debugLine="part_7 = participant.Get(5)";
Debug.ShouldStop(134217728);
_part_7.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 5))));
 BA.debugLineNum = 253;BA.debugLine="Part7.Text = \" - \"&part_7.Get(\"name\")";
Debug.ShouldStop(268435456);
qurbanstewardshipdetail.mostCurrent._part7.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_7.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 255;BA.debugLine="Dim part_8 As Map";
Debug.ShouldStop(1073741824);
_part_8 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_8", _part_8);
 BA.debugLineNum = 256;BA.debugLine="part_8 = participant.Get(6)";
Debug.ShouldStop(-2147483648);
_part_8.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 6))));
 BA.debugLineNum = 257;BA.debugLine="Part8.Text = \" - \"&part_8.Get(\"name\")";
Debug.ShouldStop(1);
qurbanstewardshipdetail.mostCurrent._part8.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_8.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 259;BA.debugLine="Part9.Visible = False";
Debug.ShouldStop(4);
qurbanstewardshipdetail.mostCurrent._part9.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 260;BA.debugLine="Part10.Visible = False";
Debug.ShouldStop(8);
qurbanstewardshipdetail.mostCurrent._part10.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 261;BA.debugLine="Part11.Visible = False";
Debug.ShouldStop(16);
qurbanstewardshipdetail.mostCurrent._part11.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 }else 
{ BA.debugLineNum = 262;BA.debugLine="Else If participant.Size = 8 Then";
Debug.ShouldStop(32);
if (RemoteObject.solveBoolean("=",_participant.runMethod(true,"getSize"),BA.numberCast(double.class, 8))) { 
 BA.debugLineNum = 263;BA.debugLine="Dim part_2 As Map";
Debug.ShouldStop(64);
_part_2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_2", _part_2);
 BA.debugLineNum = 264;BA.debugLine="part_2 = participant.Get(0)";
Debug.ShouldStop(128);
_part_2.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 0))));
 BA.debugLineNum = 265;BA.debugLine="Part2.Text = \" - \"&part_2.Get(\"name\")";
Debug.ShouldStop(256);
qurbanstewardshipdetail.mostCurrent._part2.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_2.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 267;BA.debugLine="Dim part_3 As Map";
Debug.ShouldStop(1024);
_part_3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_3", _part_3);
 BA.debugLineNum = 268;BA.debugLine="part_3 = participant.Get(1)";
Debug.ShouldStop(2048);
_part_3.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 1))));
 BA.debugLineNum = 269;BA.debugLine="Part3.Text = \" - \"&part_3.Get(\"name\")";
Debug.ShouldStop(4096);
qurbanstewardshipdetail.mostCurrent._part3.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_3.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 271;BA.debugLine="Dim part_4 As Map";
Debug.ShouldStop(16384);
_part_4 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_4", _part_4);
 BA.debugLineNum = 272;BA.debugLine="part_4 = participant.Get(2)";
Debug.ShouldStop(32768);
_part_4.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 2))));
 BA.debugLineNum = 273;BA.debugLine="Part4.Text = \" - \"&part_4.Get(\"name\")";
Debug.ShouldStop(65536);
qurbanstewardshipdetail.mostCurrent._part4.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_4.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 275;BA.debugLine="Dim part_5 As Map";
Debug.ShouldStop(262144);
_part_5 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_5", _part_5);
 BA.debugLineNum = 276;BA.debugLine="part_5 = participant.Get(3)";
Debug.ShouldStop(524288);
_part_5.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 3))));
 BA.debugLineNum = 277;BA.debugLine="Part5.Text = \" - \"&part_5.Get(\"name\")";
Debug.ShouldStop(1048576);
qurbanstewardshipdetail.mostCurrent._part5.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_5.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 279;BA.debugLine="Dim part_6 As Map";
Debug.ShouldStop(4194304);
_part_6 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_6", _part_6);
 BA.debugLineNum = 280;BA.debugLine="part_6 = participant.Get(4)";
Debug.ShouldStop(8388608);
_part_6.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 4))));
 BA.debugLineNum = 281;BA.debugLine="Part6.Text = \" - \"&part_6.Get(\"name\")";
Debug.ShouldStop(16777216);
qurbanstewardshipdetail.mostCurrent._part6.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_6.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 283;BA.debugLine="Dim part_7 As Map";
Debug.ShouldStop(67108864);
_part_7 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_7", _part_7);
 BA.debugLineNum = 284;BA.debugLine="part_7 = participant.Get(5)";
Debug.ShouldStop(134217728);
_part_7.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 5))));
 BA.debugLineNum = 285;BA.debugLine="Part7.Text = \" - \"&part_7.Get(\"name\")";
Debug.ShouldStop(268435456);
qurbanstewardshipdetail.mostCurrent._part7.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_7.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 287;BA.debugLine="Dim part_8 As Map";
Debug.ShouldStop(1073741824);
_part_8 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_8", _part_8);
 BA.debugLineNum = 288;BA.debugLine="part_8 = participant.Get(6)";
Debug.ShouldStop(-2147483648);
_part_8.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 6))));
 BA.debugLineNum = 289;BA.debugLine="Part8.Text = \" - \"&part_8.Get(\"name\")";
Debug.ShouldStop(1);
qurbanstewardshipdetail.mostCurrent._part8.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_8.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 291;BA.debugLine="Dim part_9 As Map";
Debug.ShouldStop(4);
_part_9 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_9", _part_9);
 BA.debugLineNum = 292;BA.debugLine="part_9 = participant.Get(7)";
Debug.ShouldStop(8);
_part_9.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 7))));
 BA.debugLineNum = 293;BA.debugLine="Part9.Text = \" - \"&part_9.Get(\"name\")";
Debug.ShouldStop(16);
qurbanstewardshipdetail.mostCurrent._part9.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_9.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 295;BA.debugLine="Part10.Visible = False";
Debug.ShouldStop(64);
qurbanstewardshipdetail.mostCurrent._part10.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 BA.debugLineNum = 296;BA.debugLine="Part11.Visible = False";
Debug.ShouldStop(128);
qurbanstewardshipdetail.mostCurrent._part11.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 }else 
{ BA.debugLineNum = 297;BA.debugLine="Else If participant.Size = 9 Then";
Debug.ShouldStop(256);
if (RemoteObject.solveBoolean("=",_participant.runMethod(true,"getSize"),BA.numberCast(double.class, 9))) { 
 BA.debugLineNum = 298;BA.debugLine="Dim part_2 As Map";
Debug.ShouldStop(512);
_part_2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_2", _part_2);
 BA.debugLineNum = 299;BA.debugLine="part_2 = participant.Get(0)";
Debug.ShouldStop(1024);
_part_2.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 0))));
 BA.debugLineNum = 300;BA.debugLine="Part2.Text = \" - \"&part_2.Get(\"name\")";
Debug.ShouldStop(2048);
qurbanstewardshipdetail.mostCurrent._part2.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_2.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 302;BA.debugLine="Dim part_3 As Map";
Debug.ShouldStop(8192);
_part_3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_3", _part_3);
 BA.debugLineNum = 303;BA.debugLine="part_3 = participant.Get(1)";
Debug.ShouldStop(16384);
_part_3.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 1))));
 BA.debugLineNum = 304;BA.debugLine="Part3.Text = \" - \"&part_3.Get(\"name\")";
Debug.ShouldStop(32768);
qurbanstewardshipdetail.mostCurrent._part3.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_3.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 306;BA.debugLine="Dim part_4 As Map";
Debug.ShouldStop(131072);
_part_4 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_4", _part_4);
 BA.debugLineNum = 307;BA.debugLine="part_4 = participant.Get(2)";
Debug.ShouldStop(262144);
_part_4.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 2))));
 BA.debugLineNum = 308;BA.debugLine="Part4.Text = \" - \"&part_4.Get(\"name\")";
Debug.ShouldStop(524288);
qurbanstewardshipdetail.mostCurrent._part4.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_4.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 310;BA.debugLine="Dim part_5 As Map";
Debug.ShouldStop(2097152);
_part_5 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_5", _part_5);
 BA.debugLineNum = 311;BA.debugLine="part_5 = participant.Get(3)";
Debug.ShouldStop(4194304);
_part_5.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 3))));
 BA.debugLineNum = 312;BA.debugLine="Part5.Text = \" - \"&part_5.Get(\"name\")";
Debug.ShouldStop(8388608);
qurbanstewardshipdetail.mostCurrent._part5.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_5.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 314;BA.debugLine="Dim part_6 As Map";
Debug.ShouldStop(33554432);
_part_6 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_6", _part_6);
 BA.debugLineNum = 315;BA.debugLine="part_6 = participant.Get(4)";
Debug.ShouldStop(67108864);
_part_6.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 4))));
 BA.debugLineNum = 316;BA.debugLine="Part6.Text = \" - \"&part_6.Get(\"name\")";
Debug.ShouldStop(134217728);
qurbanstewardshipdetail.mostCurrent._part6.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_6.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 318;BA.debugLine="Dim part_7 As Map";
Debug.ShouldStop(536870912);
_part_7 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_7", _part_7);
 BA.debugLineNum = 319;BA.debugLine="part_7 = participant.Get(5)";
Debug.ShouldStop(1073741824);
_part_7.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 5))));
 BA.debugLineNum = 320;BA.debugLine="Part7.Text = \" - \"&part_7.Get(\"name\")";
Debug.ShouldStop(-2147483648);
qurbanstewardshipdetail.mostCurrent._part7.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_7.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 322;BA.debugLine="Dim part_8 As Map";
Debug.ShouldStop(2);
_part_8 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_8", _part_8);
 BA.debugLineNum = 323;BA.debugLine="part_8 = participant.Get(6)";
Debug.ShouldStop(4);
_part_8.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 6))));
 BA.debugLineNum = 324;BA.debugLine="Part8.Text = \" - \"&part_8.Get(\"name\")";
Debug.ShouldStop(8);
qurbanstewardshipdetail.mostCurrent._part8.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_8.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 326;BA.debugLine="Dim part_9 As Map";
Debug.ShouldStop(32);
_part_9 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_9", _part_9);
 BA.debugLineNum = 327;BA.debugLine="part_9 = participant.Get(7)";
Debug.ShouldStop(64);
_part_9.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 7))));
 BA.debugLineNum = 328;BA.debugLine="Part9.Text = \" - \"&part_9.Get(\"name\")";
Debug.ShouldStop(128);
qurbanstewardshipdetail.mostCurrent._part9.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_9.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 330;BA.debugLine="Dim part_10 As Map";
Debug.ShouldStop(512);
_part_10 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_10", _part_10);
 BA.debugLineNum = 331;BA.debugLine="part_10 = participant.Get(8)";
Debug.ShouldStop(1024);
_part_10.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 8))));
 BA.debugLineNum = 332;BA.debugLine="Part10.Text = \" - \"&part_10.Get(\"name\")";
Debug.ShouldStop(2048);
qurbanstewardshipdetail.mostCurrent._part10.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_10.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 334;BA.debugLine="Part11.Visible = False";
Debug.ShouldStop(8192);
qurbanstewardshipdetail.mostCurrent._part11.runMethod(true,"setVisible",qurbanstewardshipdetail.mostCurrent.__c.getField(true,"False"));
 }else 
{ BA.debugLineNum = 335;BA.debugLine="Else If participant.Size = 10 Then";
Debug.ShouldStop(16384);
if (RemoteObject.solveBoolean("=",_participant.runMethod(true,"getSize"),BA.numberCast(double.class, 10))) { 
 BA.debugLineNum = 336;BA.debugLine="Dim part_2 As Map";
Debug.ShouldStop(32768);
_part_2 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_2", _part_2);
 BA.debugLineNum = 337;BA.debugLine="part_2 = participant.Get(0)";
Debug.ShouldStop(65536);
_part_2.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 0))));
 BA.debugLineNum = 338;BA.debugLine="Part2.Text = \" - \"&part_2.Get(\"name\")";
Debug.ShouldStop(131072);
qurbanstewardshipdetail.mostCurrent._part2.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_2.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 340;BA.debugLine="Dim part_3 As Map";
Debug.ShouldStop(524288);
_part_3 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_3", _part_3);
 BA.debugLineNum = 341;BA.debugLine="part_3 = participant.Get(1)";
Debug.ShouldStop(1048576);
_part_3.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 1))));
 BA.debugLineNum = 342;BA.debugLine="Part3.Text = \" - \"&part_3.Get(\"name\")";
Debug.ShouldStop(2097152);
qurbanstewardshipdetail.mostCurrent._part3.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_3.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 344;BA.debugLine="Dim part_4 As Map";
Debug.ShouldStop(8388608);
_part_4 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_4", _part_4);
 BA.debugLineNum = 345;BA.debugLine="part_4 = participant.Get(2)";
Debug.ShouldStop(16777216);
_part_4.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 2))));
 BA.debugLineNum = 346;BA.debugLine="Part4.Text = \" - \"&part_4.Get(\"name\")";
Debug.ShouldStop(33554432);
qurbanstewardshipdetail.mostCurrent._part4.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_4.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 348;BA.debugLine="Dim part_5 As Map";
Debug.ShouldStop(134217728);
_part_5 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_5", _part_5);
 BA.debugLineNum = 349;BA.debugLine="part_5 = participant.Get(3)";
Debug.ShouldStop(268435456);
_part_5.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 3))));
 BA.debugLineNum = 350;BA.debugLine="Part5.Text = \" - \"&part_5.Get(\"name\")";
Debug.ShouldStop(536870912);
qurbanstewardshipdetail.mostCurrent._part5.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_5.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 352;BA.debugLine="Dim part_6 As Map";
Debug.ShouldStop(-2147483648);
_part_6 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_6", _part_6);
 BA.debugLineNum = 353;BA.debugLine="part_6 = participant.Get(4)";
Debug.ShouldStop(1);
_part_6.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 4))));
 BA.debugLineNum = 354;BA.debugLine="Part6.Text = \" - \"&part_6.Get(\"name\")";
Debug.ShouldStop(2);
qurbanstewardshipdetail.mostCurrent._part6.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_6.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 356;BA.debugLine="Dim part_7 As Map";
Debug.ShouldStop(8);
_part_7 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_7", _part_7);
 BA.debugLineNum = 357;BA.debugLine="part_7 = participant.Get(5)";
Debug.ShouldStop(16);
_part_7.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 5))));
 BA.debugLineNum = 358;BA.debugLine="Part7.Text = \" - \"&part_7.Get(\"name\")";
Debug.ShouldStop(32);
qurbanstewardshipdetail.mostCurrent._part7.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_7.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 360;BA.debugLine="Dim part_8 As Map";
Debug.ShouldStop(128);
_part_8 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_8", _part_8);
 BA.debugLineNum = 361;BA.debugLine="part_8 = participant.Get(6)";
Debug.ShouldStop(256);
_part_8.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 6))));
 BA.debugLineNum = 362;BA.debugLine="Part8.Text = \" - \"&part_8.Get(\"name\")";
Debug.ShouldStop(512);
qurbanstewardshipdetail.mostCurrent._part8.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_8.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 364;BA.debugLine="Dim part_9 As Map";
Debug.ShouldStop(2048);
_part_9 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_9", _part_9);
 BA.debugLineNum = 365;BA.debugLine="part_9 = participant.Get(7)";
Debug.ShouldStop(4096);
_part_9.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 7))));
 BA.debugLineNum = 366;BA.debugLine="Part9.Text = \" - \"&part_9.Get(\"name\")";
Debug.ShouldStop(8192);
qurbanstewardshipdetail.mostCurrent._part9.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_9.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 368;BA.debugLine="Dim part_10 As Map";
Debug.ShouldStop(32768);
_part_10 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_10", _part_10);
 BA.debugLineNum = 369;BA.debugLine="part_10 = participant.Get(8)";
Debug.ShouldStop(65536);
_part_10.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 8))));
 BA.debugLineNum = 370;BA.debugLine="Part10.Text = \" - \"&part_10.Get(\"name\")";
Debug.ShouldStop(131072);
qurbanstewardshipdetail.mostCurrent._part10.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_10.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 BA.debugLineNum = 372;BA.debugLine="Dim part_11 As Map";
Debug.ShouldStop(524288);
_part_11 = RemoteObject.createNew ("anywheresoftware.b4a.objects.collections.Map");Debug.locals.put("part_11", _part_11);
 BA.debugLineNum = 373;BA.debugLine="part_11 = participant.Get(9)";
Debug.ShouldStop(1048576);
_part_11.setObject(_participant.runMethod(false,"Get",(Object)(BA.numberCast(int.class, 9))));
 BA.debugLineNum = 374;BA.debugLine="Part11.Text = \" - \"&part_11.Get(\"name\")";
Debug.ShouldStop(2097152);
qurbanstewardshipdetail.mostCurrent._part11.runMethod(true,"setText",BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable(" - "),_part_11.runMethod(false,"Get",(Object)((RemoteObject.createImmutable("name")))))));
 }}}}}}}}}}
;
 Debug.CheckDeviceExceptions();
} 
       catch (Exception e256) {
			BA.rdebugUtils.runVoidMethod("setLastException",qurbanstewardshipdetail.processBA, e256.toString()); BA.debugLineNum = 377;BA.debugLine="Log(LastException)";
Debug.ShouldStop(16777216);
qurbanstewardshipdetail.mostCurrent.__c.runVoidMethod ("Log",(Object)(BA.ObjectToString(qurbanstewardshipdetail.mostCurrent.__c.runMethod(false,"LastException",qurbanstewardshipdetail.mostCurrent.activityBA))));
 };
 break; }
}
;
 }else {
 BA.debugLineNum = 382;BA.debugLine="Log(\"Error: \" & Job.ErrorMessage)";
Debug.ShouldStop(536870912);
qurbanstewardshipdetail.mostCurrent.__c.runVoidMethod ("Log",(Object)(RemoteObject.concat(RemoteObject.createImmutable("Error: "),_job.getField(true,"_errormessage"))));
 BA.debugLineNum = 383;BA.debugLine="ToastMessageShow(\"Error: \" & Job.ErrorMessage, T";
Debug.ShouldStop(1073741824);
qurbanstewardshipdetail.mostCurrent.__c.runVoidMethod ("ToastMessageShow",(Object)(BA.ObjectToCharSequence(RemoteObject.concat(RemoteObject.createImmutable("Error: "),_job.getField(true,"_errormessage")))),(Object)(qurbanstewardshipdetail.mostCurrent.__c.getField(true,"True")));
 };
 BA.debugLineNum = 385;BA.debugLine="Job.Release";
Debug.ShouldStop(1);
_job.runVoidMethod ("_release");
 BA.debugLineNum = 386;BA.debugLine="End Sub";
Debug.ShouldStop(2);
return RemoteObject.createImmutable("");
}
catch (Exception e) {
			throw Debug.ErrorCaught(e);
		} 
finally {
			Debug.PopSubsStack();
		}}
public static RemoteObject  _process_globals() throws Exception{
 //BA.debugLineNum = 6;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 10;BA.debugLine="End Sub";
return RemoteObject.createImmutable("");
}
}